### PR TITLE
refs: #10 - updated to build 3.3.7 version of taiga BE and FE-dist

### PR DESCRIPTION
**Pull request by g0blin79**
Updated backend and frontend Dockerfile to install 3.3.7 version of Taiga BE and FE-dist.

Tested after build and seems to work well. I have only this error in browser console

`http://mydomain.com/api/v1/user-storage/joyride 404 (Not Found)` 

but probably depends on my local.py configuration used for test (as written here: https://github.com/taigaio/taiga-back/issues/1022).

### CODE REVIEW

**Comment by g0blin79** [comment]
Oh, I forgot:

I needed to add git package to alpine image. This because in this new version there is this line into the requirements.txt

`git+git://github.com/Python-Markdown/markdown.git@a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51 # This version solves 'infinite execution' and other issues.`

After an analysis it seems that there isn't a release of markdown that includes this commit. And I didn't want to change it to avoid failures.

**Comment by panosru** [comment]
@g0blin79 how did you solve the issue with `http://localhost/api/v1/user-storage/joyride 404 (Not Found)`?

Thanks!

**Comment by g0blin79** [comment]
@panosru sorry for the delay in response.

Sincerly I don't remember what caused that error. Probably it disappeared when I did right configuration in my local.py. Consider that I'm actually running this version of docker image on my Kubernetes production environment  (Google Cloud Platform) since last July, without problems.

Let me know if I can help you for something and (first of all) if you resolved this issue, give us more infos about that.

**Comment by panosru** [comment]
@g0blin79 no worries mate, I'm just not familiar with Python and I wasn't aware of `requirements.txt` file, so I added the line `git+git://github.com/Python-Markdown/markdown.git@a4d4b61b5ce4a7dd96ddc13c66b8716d3ad8eb51` into `requirements.txt` as you suggested and it seems to be working fine.

I have done quite a lot of changes already, currently, my setup does not look like the current repo, I took basically [that approach](https://github.com/Thram/docker-taiga) and kind of mixed a few good ideas from other repos and combined into one.

So far everything works fine, under SSL, with email notifications etc.

**Pull request merged**
